[phases.setup]
nixPkgs = ["nodejs_18"]

[phases.install]
cmds = [
  "npm install --include=dev",
  "npm install --prefix client --include=dev",
  "npm install --prefix server --include=dev"
]

[phases.build]
cmds = [
  "npm run build --prefix client"
]

[start]
cmd = "npm run start"
